{
 "title": "Test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "database", "label": "Databases", "query": { "query": "label_values(database)" } },
   { "name": "instance", "label": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Параметры транзакций на $database",
   "type": "timeseries",
   "description": "NT-OIT - эта разница показывает количество мусора в базе данных. По этому параметру можно судить о целесообразности резервного копирования.\nOIT - OST - эта разница показывает как скоро произойдёт сборка мусора: если значение равно значению sweep interval - происходит сборка, иначе сборки мусора нет.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "transactions_params{database=\"$database\", instance=\"$instance\", type=\"NT\"} - ignoring(type) transactions_params{database=\"$database\", instance=\"$instance\", type=\"OIT\"}",
     "legendFormat": "NT-OIT"
    },
    {
     "expr": "transactions_params{database=\"$database\", instance=\"$instance\", type=\"OIT\"} - ignoring(type) transactions_params{database=\"$database\", instance=\"$instance\", type=\"OST\"}",
     "legendFormat": "OIT - OST"
    }
   ]
  },
  {
   "title": "Соединения с $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "amount_of_attachments{database=\"$database\", instance=\"$instance\"}",
     "legendFormat": "Количество"
    }
   ]
  },
  {
   "title": "Объём базы данных",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{database=\"$database\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage (free)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_disks{instance=\"$instance\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_cpu{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RAM (free)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_memory{instance=\"$instance\"}) by (type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM (СУБД)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mon_memory_usage{database=\"$database\", instance=\"$instance\", stat_group=\"database\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RAM (СУБД транзакции)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mon_memory_usage{database=\"$database\", instance=\"$instance\", stat_group=\"transaction\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RAM (СУБД соединения)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mon_memory_usage{database=\"$database\", instance=\"$instance\", stat_group=\"connection\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RAM (СУБД запросы)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mon_memory_usage{database=\"$database\", instance=\"$instance\", stat_group=\"statement\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RAM (СУБД вызовы)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mon_memory_usage{database=\"$database\", instance=\"$instance\", stat_group=\"call\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество fetches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"database\", type=\"page_fetches\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"database\", type=\"page_reads\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"database\", type=\"page_writes\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество marks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"database\", type=\"page_marks\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество fetches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"connection\", type=\"page_fetches\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"connection\", type=\"page_reads\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"connection\", type=\"page_writes\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество marks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"connection\", type=\"page_marks\"})",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество fetches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"transaction\", type=\"page_fetches\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"transaction\", type=\"page_reads\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"transaction\", type=\"page_writes\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество marks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"transaction\", type=\"page_marks\"})",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество fetches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"statement\", type=\"page_fetches\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"statement\", type=\"page_reads\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"statement\", type=\"page_writes\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество marks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"statement\", type=\"page_marks\"})",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Calls I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество fetches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"call\", type=\"page_fetches\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"call\", type=\"page_reads\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"call\", type=\"page_writes\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество marks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum(mon_io_stats{database=\"$database\", instance=\"$instance\", stat_group=\"call\", type=\"page_marks\"})",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}